### ISSUE TITLE
Prices for buying and selling items

### ISSUE THREAD

**Issue by Midnighit** [bigmanshawn/ConanEvolved_Merchants#11]
Selling low amounts of items can be exploited as the price always seems to be rounded up to at least 1 gold. Example: [http://i.imgur.com/rvSkVDk.jpg](url)

Conversely with buying from the merchant allows you to buy more of a given item than you should be able to. The code is already smart that way by not allowing you to buy less than what you'd get for 1 gold.
I suggest applying the same logic for values over 1 gold and for selling items.

Example:
If you **buy** 29 items for 0.05 = 1.45 that'd either round up to 2 or - if available - give 40 of said item.
If you **sell** 3 items for 0.03 = 0.09 the merchant either doesn't allow it entirely or you'd simply not get anything for it
If you **sell** 60 items for 0.03 = 1.8 the merchant would only take 34 of them and give you 1 gold for it.

**Comment by bigmanshawn** [comment]
Working on this now.  The math is a little outside my normal expertise.  I am making it so you cant sell unless you equal 1 gold or more.  but I would like to make it so it only lets you sell in quantities that equal whole golds so just need to do the math for that, will work both ways.  So buying you can only buy in quantities that equal whole golds.

**Comment by bigmanshawn** [comment]
Have writte functionality so that a player must sell a quantity that will = a gold.  This can get a little bit akward due to the the price mark down from the traveling merchant, For instance 1.6 * 0.6 = .995 or something like that which comes out to requiring selling 25 to get exactly 24 gold vs the 5 that would be required for 1.6.  Not ideal but going with it for now and we may switch it around later to work the other way for sanity.  Make the markdown a mark up instead so that people sell at base price and merchant sells at marked up price.

**Comment by bigmanshawn** [comment]
Resolved with 42e249550ef152af185736d336fbd15494c615da
