### ISSUE TITLE
Buying large amounts of items (tested for 5k+ items) reproducibly resulted in no money being deducted.

### ISSUE THREAD

**Issue by Midnighit** [bigmanshawn/ConanEvolved_Merchants#13]
Example: buying 5500 bark for 0.05 each which should cost 275 coins
The amount is correctly being calculated [http://i.imgur.com/dmGzk64.jpg](url)
but not actually withdrawn [http://i.imgur.com/YsLzu8c.jpg](url)

Since this problem is likely caused by some rounding error, it's quite possible that it has already been fixed with the fix of issue #11

**Comment by bigmanshawn** [comment]
Will test, wondering if there is some kind of failure in the part of the engine that evaluates the gold.  I might be giving items then taking gold if the move was successful, but then the gold may be failing without throwing an error.  The gold movement code is somwhat complex since it stacks and unstacks gold so it doesnt just fill your inventory with single pieces.

**Comment by bigmanshawn** [comment]
So this one actually took a little bit to puzzle out.  It was not that the money wasn't being moved, the problem was a bug with Collect Gold for merchant owners.  It was adding to your stack, and then giving you another stack of the amount moved (so effectively giving you twice the gold that was on the Merchant).  What then happens is because your inventory is full that gold is in a pile at the bottom off screen, so you dont see it moving when you buy stuff.  This has been fixed in commit
